version: '3.8'
services:
  redis:
    build: ./redis
    container_name: redis_cache
    ports:
      - "6379:6379"  # Redis default port
    networks:
      - fog_network
    deploy:
      resources:
        limits:
          memory: 1g  # Redis 500MB memory
          cpus: "1.0"   # Redis 1 CPU core

  manager:
    build: ./manager
    container_name: manager
    networks:
      - fog_network
    depends_on:
      - redis
    ports:
      - "6000:6000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          memory: 1g  # Manager 1GB memory
          cpus: "1.0"  # Manager 1 CPU core

  fog_node1:
    build: ./fog_nodes
    container_name: fog_node1
    environment:
      - FOG_NODE_NUMBER=1
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - fog_network
    depends_on:
      - redis
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 1g  # Fog Node 1GB memory
          cpus: "1.0"  # Fog Node 1 CPU core

  fog_node2:
    build: ./fog_nodes
    container_name: fog_node2
    environment:
      - FOG_NODE_NUMBER=2
      - PORT=5001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - fog_network
    depends_on:
      - redis
    ports:
      - "5001:5001"
    deploy:
      resources:
        limits:
          memory: 1g  # Fog Node 1GB memory
          cpus: "1.0"  # Fog Node 1 CPU core

  fog_node3:
    build: ./fog_nodes
    container_name: fog_node3
    environment:
      - FOG_NODE_NUMBER=3
      - PORT=5002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - fog_network
    depends_on:
      - redis
    ports:
      - "5002:5002"
    deploy:
      resources:
        limits:
          memory: 1g  # Fog Node 1GB memory
          cpus: "1.0"  # Fog Node 1 CPU core

  iot_device:
    build: ./iot_device
    container_name: iot_device
    networks:
      - fog_network
    stdin_open: true  # Keep container open for interaction
    tty: true  # Allow interactive shell
    depends_on:
      - manager
    deploy:
      resources:
        limits:
          memory: 1g  # IoT Device 1GB memory
          cpus: "1.0"  # IoT Device 1 CPU core

networks:
  fog_network:
    driver: bridge

